# Project Information
site_name: Agentic Risk & Capability Framework
site_author: GovTech AI Practice
copyright: GovTech Singapore
docs_dir: docs
repo_url: https://github.com/govtech-responsibleai/agentic-risk-capability-framework

# Theme Configuration
theme:
  name: material
  features:
    - toc.integrate
    - toc.follow
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.footer
    - navigation.path
    - navigation.expand
  palette:
    scheme: default
    primary: white
    accent: blue
  icon: 
    logo: material/shield-star
    favicon: material/shield-star

markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Extra Configuration
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/orgs/govtech-responsibleai/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/govtech-singapore
    - icon: fontawesome/brands/twitter
      link: https://x.com/GovTechSG
  analytics:
    provider: google
    property: G-VDHLWLGZ1W
    feedback: 
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://forms.gle/KoXecxDuPHf8izP2A" target="_blank" rel="noopener">feedback form</a>.
    
# Navigation
nav:
  - Introduction: 
    - index.md
    - Why the ARC Framework?: intro/why_arc.md
    - About the ARC Framework: intro/about_arc.md
  - Baseline: 
    - What is a Baseline?: baseline/index.md
    - Baseline Risks: baseline/risks.md
    - Baseline Controls: baseline/controls.md
  - Capability:
    - What is a Capability?: capability/index.md
    - Risks: capability/risks.md
    - Controls: capability/controls.md
  - Implementation:
    - Implementing ARC: implementation/index.md
    - For Governance Teams: implementation/for-governance-teams.md
    - For AI Developers: implementation/for-ai-developers.md
# Plugins
plugins:
  - search
  - section-index
